
-- DENTALDE CLINIC - Supabase schema
-- Supabase SQL Editor > New Query içine yapıştırıp RUN bas.

create table if not exists hastalar (
  id bigint generated by default as identity primary key,
  hasta_adi text not null,
  tc text,
  telefon text,
  dogum_tarihi date,
  kronik_hastalik text,
  kullanilan_ilaclar text,
  alerji text,
  kanser_gecmisi text,
  operasyon_gecmisi text,
  hamilelik_durumu text,
  kanama_pihtilasma text,
  sistemik_notlar text,
  notlar text,
  created_at timestamptz default now()
);

create table if not exists ayarlar (
  id bigint generated by default as identity primary key,
  grup text not null,
  deger text not null,
  renk text,
  created_at timestamptz default now()
);

create table if not exists islemler (
  id bigint generated by default as identity primary key,
  kod text,
  kategori text,
  islem_adi text not null,
  kdv_dahil_ucret numeric default 0,
  sure_dk integer default 30,
  dis_no_gerekli boolean default false,
  durum text default 'Aktif',
  created_at timestamptz default now()
);

create table if not exists randevular (
  id bigint generated by default as identity primary key,
  tarih date not null,
  saat text not null,
  hasta_adi text not null,
  hekim text,
  oda text,
  islem_id text,
  islem_adi text,
  dis_no text,
  ucret numeric default 0,
  sure_dk integer default 30,
  durum text,
  notlar text,
  created_at timestamptz default now()
);

create table if not exists hasta_islemleri (
  id bigint generated by default as identity primary key,
  tarih date not null,
  saat text,
  hasta_adi text not null,
  islem_id text,
  islem_adi text,
  kategori text,
  dis_no text,
  hekim text,
  ucret numeric default 0,
  sure_dk integer default 30,
  durum text default 'Planlandı',
  randevu_id bigint,
  lab_gidecek boolean default false,
  notlar text,
  created_at timestamptz default now()
);

create table if not exists odemeler (
  id bigint generated by default as identity primary key,
  tarih date not null,
  hasta_adi text not null,
  tutar numeric not null default 0,
  odeme_tipi text,
  aciklama text,
  created_at timestamptz default now()
);

create table if not exists giderler (
  id bigint generated by default as identity primary key,
  tarih date not null,
  gider_tipi text,
  tutar numeric not null default 0,
  odeme_tipi text,
  hasta_adi text,
  islem_row_id bigint,
  aciklama text,
  created_at timestamptz default now()
);

create table if not exists laboratuvar (
  id bigint generated by default as identity primary key,
  tarih date not null,
  hasta_adi text not null,
  islem_row_id bigint,
  islem_adi text,
  lab_adi text,
  gonderim_tarihi date,
  teslim_tarihi date,
  lab_ucreti numeric default 0,
  durum text default 'Gönderilecek',
  aciklama text,
  created_at timestamptz default now()
);

insert into ayarlar (grup, deger, renk)
select * from (values
  ('hekim','Dr.Dt. M. Enes MARAŞ','#9ACD32'),
  ('hekim','Dt. S. Deniz MARAŞ','#111111'),
  ('oda','Clinic 1','#9ACD32'),
  ('oda','Clinic 2','#111111'),
  ('durum','Planlandı',null),
  ('durum','Geldi',null),
  ('durum','Tamamlandı',null),
  ('durum','İptal',null),
  ('durum','Ertelendi',null),
  ('odeme','Nakit',null),
  ('odeme','Kredi Kartı',null),
  ('odeme','Havale/EFT',null),
  ('gider','Laboratuvar',null),
  ('gider','Malzeme',null),
  ('gider','Kira',null),
  ('gider','Personel',null),
  ('gider','Fatura',null),
  ('gider','Diğer',null),
  ('lab','Laboratuvar 1',null),
  ('lab_durum','Gönderilecek',null),
  ('lab_durum','Gönderildi',null),
  ('lab_durum','Teslim Alındı',null),
  ('lab_durum','Hastaya Takıldı',null),
  ('lab_durum','İptal',null)
) as v(grup,deger,renk)
where not exists (select 1 from ayarlar);

insert into islemler (kod, kategori, islem_adi, kdv_dahil_ucret, sure_dk, dis_no_gerekli, durum)
select * from (values
  ('1-1','Teşhis ve Tedavi Planlaması','Dişhekimi Muayenesi',1650,20,false,'Aktif'),
  ('2-4','Tedavi ve Endodonti','Kompozit Dolgu (Bir Yüzlü)',3375,45,true,'Aktif'),
  ('2-27','Tedavi ve Endodonti','Kanal Tedavisi - Tek Kanal',4610,60,true,'Aktif'),
  ('4-51','Protez','Zirkonyum Kron',13750,60,true,'Aktif'),
  ('5-1','Ağız-Diş ve Çene Cerrahisi','Diş Çekimi',2475,30,true,'Aktif'),
  ('6-1','Periodontoloji','Detartraj (Diş Taşı Temizliği - Tek Çene)',3300,45,false,'Aktif')
) as v(kod,kategori,islem_adi,kdv_dahil_ucret,sure_dk,dis_no_gerekli,durum)
where not exists (select 1 from islemler);
